### ISSUE TITLE
`renderFormatted()` adds empty lines after `img` and `svg`

### ISSUE THREAD

**Issue by christophhagen** [sliemeobn/elementary#16]
When rendering HTML with `renderFormatted()`, there are many empty lines added after `img` and `svg` elements.

In my test, there were 12 empty lines after an `img` element, and 3 lines after each `svg` element.
The lines are all indented to the previous element.

**Comment by sliemeobn** [comment]
yeah, the renderFormatted() bit is a lot more complicated to get right than one would think.

To be honest, I have noticed this too and I am thinking about removing the API entirely to keep the maintenance burden low. if someone spots a quick fix: happy to merge a PR ; )

**Comment by sliemeobn** [comment]
the latest release contains a bigger refactor of the formatter and so far things seem to be ok.
please reopen if there are still issues with it.
