### ISSUE TITLE
Use pretty HTML renderer as default

### ISSUE THREAD

**Issue by mapedd** [sliemeobn/elementary#48]
Seems other HTML renderers add new lines and spaces to render actual HTML.
Elementary renders (by default) everything in single line which make code inspection in the browser much harder. 
I presume it's for added performance but not sure it's necessary, what are your thoughts?
Could the default be changed or at least possible to configure it to do pretty rendering?

**Comment by sliemeobn** [comment]
honestly, I came to the opposite conclusion: 
browser dev tools will format HTML by default anyway (both chrome and safari, in both the DOM view as well as the network views).
so, to me, adding both the complexity and runtime overhead for producing something ultimately unnecessary is simply not warranted.

it is surprisingly hard to "correctly" format HTML without messing up inline-style elements (and as far as I can tell other libraries actually get that wrong, adding unexpected whitespaces in places where they matter).
especially with a streaming-first approach, it is just not something I want to pursue.

**Comment by mapedd** [comment]
ok, I understand your reasoning. 

I can't find a way to format HTML for reading when clicking View Source in Chrome, I see single line whereas other websites show somewhat normal looking HTML

**Comment by sliemeobn** [comment]
_> I can't find a way to format HTML for reading when clicking View Source in Chrome_

I highly suggest you use the developer tool (right-click > Inspect) instead. thank me later ; )
