### ISSUE TITLE
Append HTMLElement to string

### ISSUE THREAD

**Issue by Riyyi** [sliemeobn/elementary#56]
Hello, this package is pretty interesting, it made me look into Swift and Vapor.

I'm trying to make a table head with a piece of text and a bootstrap icon after it, separated by a space. Basically append an HTML element to a piece of text. The `HTMLElement` constructor does not have an empty variant, how would I solve this?

```swift
table(.class("table")) {
    thead {
        tr {
            // I tried
            th { "Title "; i(.class("bi bi-arrow-down-circle")) }
            th { HTMLText("Title "); i(.class("bi bi-arrow-down-circle")) }

            // Maybe this could be something to add? It could be called empty/notag
            th { empty {"Title "}; i(.class("bi bi-arrow-down-circle")) }

            // I guess using an existing unstyled HTML tag is a work-around
            th { span {"Title "}; i(.class("bi bi-arrow-down-circle")) }
        }
    }
```

The last line gives me this compiler error, however, so I must be misunderstanding something:

`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions (lsp)`

**Comment by sliemeobn** [comment]
hi,

I think the only issue here is that the `i` tag needs content (ie: a closure).

this should work just fine:
```swift
table(.class("table")) {
            thead {
                tr {
                    th { "Title "; i(.class("bi bi-arrow-down-circle")) {} }
                }
            }
        }
```

To make things more readable, you can always introduce new components like this:
```swift
struct TextWithIcon: HTML {
    var text: String
    var icon: String

    init(_ text: String, bi icon: String) {
        self.text = text
        self.icon = icon
    }

    var content: some HTML {
        "\(text) "
        i(.class("bi \(bi)")) {}
    }
}

// used like this
  table(.class("table")) {
      thead {
          tr {
              th { TextWithIcon("Hello", bi: "bi-arrow-down-circle") }
          }
      }
  }
```

**Comment by Riyyi** [comment]
Your suggestion works, I cant believe thats the only I hadnt tried out of all the combinations. Thanks!
